version: "3.9"

services:
    postgres:
        image: postgres:latest
        container_name: takedb
        ports:
            - 7401:5432
        volumes:
            - "/dockerVolumes/take-initiative/postgresql:/var/lib/postgresql/data"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        restart: always
    api:
        build:
            context: ./apps/TakeInitiative.Api/
        container_name: takeapi
        ports:
            - "7402:8080"
        environment:
            - "ConnectionStrings:TakeDB=User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;"
            - "CORS:MainApp=http://localhost:7403;https://localhost:7403"
            - "CORS:AdminApp=http://localhost:7404;https://localhost:7404"
            - "AllowedHosts=localhost"
            - "CookieDomain=localhost"
        restart: always
        # healthcheck:
        #     test: curl --fail http://localhost:8080/heathz || exit 1
        #     interval: 60s
        #     retries: 5
        #     start_period: 20s
        #     timeout: 10s
    web:
        build:
            context: ./apps/TakeInitiative.Web/
            dockerfile: ./dockerfile.Main
        container_name: takeweb
        ports:
            - "7403:3000"
        environment:
            - "NUXT_PUBLIC_AXIOS_BASE_URL=https://localhost:7402"
            - "NUXT_PUBLIC_WEB_URL=http://localhost:7403"
        restart: always
    admin:
        build:
            context: ./apps/TakeInitiative.Web/
            dockerfile: ./dockerfile.Admin
        container_name: takeadmin
        ports:
            - "7404:3000"
        environment:
            - "NUXT_PUBLIC_AXIOS_BASE_URL=https://localhost:7402"
            - "NUXT_PUBLIC_WEB_URL=http://localhost:7403"
            - "NUXT_PUBLIC_ADMIN_URL=http://localhost:7404"
        restart: always
