version: "3.9"

services:
    postgres:
        image: postgres:latest
        container_name: takedb
        ports:
            - 7401:5432
        volumes:
            - "/dockerVolumes/take-initiative/postgresql:/var/lib/postgresql/data"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        restart: always
    api:
        build:
            context: ./apps/TakeInitiative.Api/
        container_name: takeapi
        ports:
            - "7402:8080"
        environment:
            - "ConnectionStrings:TakeDB=User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;"
            - "CORS=http://take-initiative.com;https://take-initiative.com"
            - "AllowedHosts=api.take-initiative.com"
            - "CookieDomain=take-initiative.com"
        restart: always
        # healthcheck:
        #     test: curl --fail http://localhost:8080/heathz || exit 1
        #     interval: 60s
        #     retries: 5
        #     start_period: 20s
        #     timeout: 10s
    web:
        build:
            context: ./apps/TakeInitiative.Web/
        container_name: takeweb
        ports:
            - "7403:3000"
        environment:
            - "NUXT_PUBLIC_AXIOS_BASE_URL=https://api.take-initiative.com"
            - "NUXT_PUBLIC_WEB_URL=https://take-initiative.com"
        restart: always
