version: "3.9"

services:
    postgres:
        image: postgres:latest
        container_name: takedb
        ports:
            - 5432:5432
        volumes:
            - "/dockerVolumes/take-initiative/postgresql:/var/lib/postgresql/data"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        restart: always
    api:
        image: takeinitiative-api:latest
        container_name: takeapi
        ports:
            - "5000:8080"
        environment:
            - "ConnectionStrings:TakeDB=User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;"
            - "CORS=https://take-initiative.com;https://take-initiative.com"
            - "AllowedHosts=api.take-initiative.com"
        restart: always
    web:
        build: takeinitiative-web:latest
        container_name: takeweb
        ports:
            - "3000:3000"
        environment:
            - "NUXT_PUBLIC_AXIOS_BASE_URL=https://api.take-initiative.com"
        restart: always
