# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Api

on:
    push:
        branches: ["dev"]
        paths:
            - "**.cs"
            - "**.csproj"
    pull_request:
        branches: ["dev"]
        paths:
            - "**.cs"
            - "**.csproj"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - name: Set up Python
              # This is the version of the action for setting up Python, not the Python version.
              uses: actions/setup-python@v5
              with:
                  # Semantic version range syntax or exact version of a Python version
                  python-version: "3.11"
            - name: "Get python location"
              run: |
                  which python | ls
            # - name: Restore dependencies
            #   run: dotnet restore
            # - name: Build
            #   run: dotnet build --configuration Release --no-restore
            # - name: Test
            #   run: dotnet test -- --verbosity normal
