# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Api

on:
    push:
        branches: ["dev"]
        paths:
            - "**.cs"
            - "**.csproj"
    pull_request:
        branches: ["dev"]
        paths:
            - "**.cs"
            - "**.csproj"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip" # caching pip dependencies
            # - name: "Find python libpython3.11.so"
            #   run: |
            #       find / -name libpython3.11.so
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: |
                  dotnet build --configuration Release --no-restore
            - name: Test
              run: |
                  export PythonDLL=/opt/hostedtoolcache/Python/3.11.9/x64/lib/libpython3.11.so
                  dotnet test -- --verbosity normal
