# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Web

on:
    push:
        branches: ["dev"]
        paths:
            - ".github\workflows\testWeb.yml"
            - "**.vue"
            - "**.ts"
    pull_request:
        branches: ["dev"]
        paths:
            - ".github\workflows\testWeb.yml" 
            - "**.vue"
            - "**.ts"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Run Typecheck
              run: |
                  cd ./apps/TakeInitiative.Web
                  npm ci
                  npx nuxi typecheck
